=== kermodero/testapp-cgmrenewal/adprenewal/src/main/resources/GM_renewal_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:element name="form1">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Form">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="formType" />
							<xs:element type="xs:string" name="deviceCategory" />
							<xs:element type="xs:string" name="VersionNumber" />
							<xs:element name="section1">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="applicantLastname" />
										<xs:element type="xs:string" name="applicantFirstname" />
										<xs:element type="xs:string" name="applicantMiddleinitial" />
										<xs:element type="xs:string" name="healthNo" />
										<xs:element type="xs:string" name="versionNo" />
										<xs:element type="xs:string" name="DateOfBirth" />
										<xs:element type="xs:string" name="sex" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="section2">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="question1" />
										<xs:element type="xs:string" name="question2" />
										<xs:element type="xs:string" name="question3" />
										<xs:element type="xs:string" name="certification" />
										<xs:element type="xs:string" name="signedBy" />
										<xs:element type="xs:string" name="signature" />
										<xs:element type="xs:string" name="signDate" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="section3">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="contact">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="relationship" />
													<xs:element type="xs:string" name="agentLastname" />
													<xs:element type="xs:string" name="agentFirstname" />
													<xs:element type="xs:string" name="agentMiddleinitial" />
													<xs:element type="xs:string" name="agentUnitNo" />
													<xs:element type="xs:string" name="agentStreetNo" />
													<xs:element type="xs:string" name="agentStreetName" />
													<xs:element type="xs:string" name="agentRRoute" />
													<xs:element type="xs:string" name="agentCity" />
													<xs:element type="xs:string" name="agentProvince" />
													<xs:element type="xs:string" name="agentPostalCode" />
													<xs:element type="xs:string" name="agentHomePhone" />
													<xs:element type="xs:string" name="agentBusPhone" />
													<xs:element type="xs:string" name="agentPhoneExtension" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="section4">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="vendor">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="vendorBusName" />
													<xs:element type="xs:string" name="adpVendorRegNo" />
													<xs:element type="xs:string" name="vendorLastname" />
													<xs:element type="xs:string" name="vendorFirstname" />
													<xs:element type="xs:string" name="vendorPositionTitle" />
													<xs:element type="xs:string" name="vendorBusPhone" />
													<xs:element type="xs:string" name="vendorPhoneExtension" />
													<xs:element type="xs:string" name="vendorUnitNo" />
													<xs:element type="xs:string" name="vendorStreetNo" />
													<xs:element type="xs:string" name="vendorStreetName" />
													<xs:element type="xs:string" name="vendorCity" />
													<xs:element type="xs:string" name="vendorProvince" />
													<xs:element type="xs:string" name="vendorPostalCode" />
													<xs:element type="xs:string" name="vendorSignature" />
													<xs:element type="xs:string" name="vendorSignDate" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== kermodero/testapp-cgmrenewal/adprenewal/src/main/resources/GM_renewal.xml
<?xml version="1.0" encoding="UTF-8"?>
<form1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GM_renewal_schema.xsd">
  <Form>
    <formType>RENEWAL</formType>
    <deviceCategory>GM</deviceCategory>
    <VersionNumber>202311</VersionNumber>
    <section1>
      <applicantLastname>applicantLastname</applicantLastname>
      <applicantFirstname>applicantFirstname</applicantFirstname>
      <applicantMiddleinitial>applicantMiddleinitial</applicantMiddleinitial>
      <healthNo>healthNo</healthNo>
      <versionNo>versionNo</versionNo>
      <DateOfBirth>DateOfBirth</DateOfBirth>
      <sex>sex</sex>
    </section1>
    <section2>
      <question1>question1</question1>
      <question2>question2</question2>
      <question3>question3</question3>
      <certification>certification</certification>
      <signedBy>signedBy</signedBy>
      <signature>signature</signature>
      <signDate>signDate</signDate>
    </section2>
    <section3>
      <contact>
        <relationship>relationship</relationship>
        <agentLastname>agentLastname</agentLastname>
        <agentFirstname>agentFirstname</agentFirstname>
        <agentMiddleinitial>agentMiddleinitial</agentMiddleinitial>
        <agentUnitNo>agentUnitNo</agentUnitNo>
        <agentStreetNo>agentStreetNo</agentStreetNo>
        <agentStreetName>agentStreetName</agentStreetName>
        <agentRRoute>agentRRoute</agentRRoute>
        <agentCity>agentCity</agentCity>
        <agentProvince>agentProvince</agentProvince>
        <agentPostalCode>agentPostalCode</agentPostalCode>
        <agentHomePhone>agentHomePhone</agentHomePhone>
        <agentBusPhone>agentBusPhone</agentBusPhone>
        <agentPhoneExtension>agentPhoneExtension</agentPhoneExtension>
      </contact>
    </section3>
    <section4>
      <vendor>
        <vendorBusName>vendorBusName</vendorBusName>
        <adpVendorRegNo>adpVendorRegNo</adpVendorRegNo>
        <vendorLastname>vendorLastname</vendorLastname>
        <vendorFirstname>vendorFirstname</vendorFirstname>
        <vendorPositionTitle>vendorPositionTitle</vendorPositionTitle>
        <vendorBusPhone>vendorBusPhone</vendorBusPhone>
        <vendorPhoneExtension>vendorPhoneExtension</vendorPhoneExtension>
        <vendorUnitNo>vendorUnitNo</vendorUnitNo>
        <vendorStreetNo>vendorStreetNo</vendorStreetNo>
        <vendorStreetName>vendorStreetName</vendorStreetName>
        <vendorCity>vendorCity</vendorCity>
        <vendorProvince>vendorProvince</vendorProvince>
        <vendorPostalCode>vendorPostalCode</vendorPostalCode>
        <vendorSignature>vendorSignature</vendorSignature>
        <vendorSignDate>vendorSignDate</vendorSignDate>
      </vendor>
    </section4>
  </Form>
</form1>
